# Generated by Django 2.1.2 on 2018-10-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
        migrations.AlterModelTable(
            name='media',
            table='media',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
