# Generated by Django 2.1.2 on 2018-11-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181104_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='user_tags', to='api.Tag'),
        ),
    ]
