# Generated by Django 2.1.2 on 2018-11-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181115_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
    ]
