# Generated by Django 2.1.2 on 2018-11-15 22:17

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181115_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='media',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='media',
            name='url',
        ),
        migrations.AddField(
            model_name='event',
            name='featured_image',
            field=models.FileField(blank=True, null=True, upload_to=api.models.file_upload_path),
        ),
        migrations.AddField(
            model_name='media',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='api.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(default='', upload_to=api.models.file_upload_path),
            preserve_default=False,
        ),
    ]
