# Generated by Django 2.1.2 on 2019-01-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190106_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='corporate_profile',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.CorporateUserProfile'),
        ),
    ]
